<a href="https://colab.research.google.com/github/pspvv/ML_Workshop/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practical Machine Learning Assignment-1

In [ ]:
import numpy as np

####1. Perform arithmetic operations on NumPy arrays

In [ ]:
a=np.array([10,20,30,40,50])
b=np.array([10,5,20,15,30])
c=np.array([9,16,25,36,49])
print("Addition",np.add(a,b))
print("Subtraction",a-b)
print("Multiplication",a*b)
print("Division",np.divide(a,b))
print("Dot product of a and square root of c",a@np.sqrt(c))

Addition [20 25 50 55 80]
Subtraction [ 0 15 10 25 20]
Multiplication [ 100  100  600  600 1500]
Division [1.         4.         1.5        2.66666667 1.66666667]
Dot product of a and square root of c 850.0


####2. Write a script to compute the mean and standard deviation of a NumPy array.

In [ ]:
a=np.array([1,3,5,2,4,6,11,14])
print("Mean",np.mean(a))
print("Standard deviation",np.std(a))

Mean 5.75
Standard deviation 4.235268586524354


####3. Create a NumPy array of integers from 10 to 50 with a step size of 5

In [ ]:
arr=np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]


####4. Reshape the array into a 2x4 matrix.

In [ ]:
res_arr=a.reshape(2,4)
print(res_arr)

[[ 1  3  5  2]
 [ 4  6 11 14]]


####5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
  • Extract the sub-matrix containing the last two rows and first two columns.
  
  • Replace all elements greater than 4 with 0.

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Extracted array",arr[1:,:2])
arr[arr>4]=0
print("Array after replacing",arr)

Extracted array [[4 5]
 [7 8]]
Array after replacing [[1 2 3]
 [4 0 0]
 [0 0 0]]


####6. Create two 1D arrays:
• a = np.array([1, 2, 3])

• b = np.array([4, 5, 6])

• Perform element-wise addition, multiplication, and division

In [ ]:
a=np.array([13,25,30])
print("Addition",a+5)
print("Multiplication",a*7)
print("Division",a/10)

Addition [18 30 35]
Multiplication [ 91 175 210]
Division [1.3 2.5 3. ]


####7. Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.

• Maximum value of the entire array.

• Sum of all elements.

In [ ]:
e=np.random.random((4,4))
print(e)
print("Meaan of each ccoolumn",np.mean(e,axis=0))
print("Maximum value of array",np.max(e))
print("Sum of all elements",np.sum(e))

[[0.15836173 0.7465512  0.50933819 0.61579428]
 [0.52509042 0.18800302 0.65881757 0.07393939]
 [0.69647593 0.73510204 0.12197442 0.62889118]
 [0.83790669 0.43465756 0.63706105 0.5564147 ]]
Meaan of each ccoolumn [0.55445869 0.52607846 0.48179781 0.46875989]
Maximum value of array 0.8379066907344331
Sum of all elements 8.124379382187037


####8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2.

In [ ]:
arr=np.array([1,2,3,4])
print((arr+10)*2)

[22 24 26 28]


####9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:

• Extract the second "layer" (i.e., the second 2D array) in the first dimension.

• Extract the first two rows and the last three columns from each "layer."

• Replace all elements divisible by 3 with -1.

In [ ]:
a=np.random.randint(1,101,size=(3,4,5))
print("Second layer",a[1])#we can also use this:- a[1,:,:]
print("Sub-array:",a[:,:2,-3:])
a[a%3==0]=-1
print("Replaced array",a)

Second layer [[ 65  62  57  48  19]
 [ 84 100  81  75  33]
 [ 74  65  41  97  46]
 [ 80  78  78  69  65]]
Sub-array: [[[67 26 48]
  [58 83 17]]

 [[57 48 19]
  [81 75 33]]

 [[16 99 95]
  [34  5 53]]]
Replaced array [[[ 34  -1  67  26  -1]
  [ 53  34  58  83  17]
  [ 35  -1  -1  -1  94]
  [ -1  98  31  -1  -1]]

 [[ 65  62  -1  -1  19]
  [ -1 100  -1  -1  -1]
  [ 74  65  41  97  46]
  [ 80  -1  -1  -1  65]]

 [[ -1  80  16  -1  95]
  [ -1  28  34   5  53]
  [ -1  -1  95  -1  64]
  [ 58   8  73  10  -1]]]


####10. Work with broadcasting and advanced operations in NumPy.
Create a NumPy array arr of shape (3, 3) with random integers between
1 and 20. Perform the following:

• Subtract the mean of each row from its respective elements (row-wise
normalization).

• Create a new array by squaring all the elements in arr.

• Find the indices of the top 3 maximum values in the entire array.

In [ ]:
arr=np.random.randint(1,21,size=(3,3))
print("Random array",arr)
print("Normalized array",arr-arr.mean(axis=1,keepdims=True))
sqarr=arr**2
print("squared array",sqarr)
flat_arr = arr.flatten()
top_3_indices = np.argpartition(flat_arr, -3)[-3:]
row_indices, col_indices = np.unravel_index(top_3_indices, arr.shape)
print("Indices of top 3 maximum values:")
for i in range(3):
    print(f"Value: {arr[row_indices[i]][col_indices[i]]}, Index: ({row_indices[i]}, {col_indices[i]})")

Random array [[14 18  5]
 [18  4 16]
 [ 2  9 15]]
Normalized array [[ 2  6 -7]
 [ 6 -8  4]
 [-6  1  7]]
squared array [[196 324  25]
 [324  16 256]
 [  4  81 225]]
Indices of top 3 maximum values:
Value: 16, Index: (1, 2)
Value: 18, Index: (1, 0)
Value: 18, Index: (0, 1)
